<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcd73fc644f705cf9a410cf73b9e87fad
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SergeR\\CakeUtility\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SergeR\\CakeUtility\\' => 
        array (
            0 => __DIR__ . '/..' . '/serger/cake-utility/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcd73fc644f705cf9a410cf73b9e87fad::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcd73fc644f705cf9a410cf73b9e87fad::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
